-- 부서 테이블
CREATE TABLE departments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(100) NOT NULL UNIQUE,
                             description TEXT,
                             established_date DATE NOT NULL,
                             created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                             updated_at TIMESTAMPTZ
);

CREATE INDEX idx_departments_name ON departments(name);

-- 파일 테이블
CREATE TABLE files (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       file_name VARCHAR(255) NOT NULL,
                       format VARCHAR(50) NOT NULL,
                       size BIGINT NOT NULL,
                       file_path VARCHAR(255) NOT NULL,
                       created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 직원 테이블
CREATE TABLE employees (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(100) NOT NULL,
                           email VARCHAR(255) NOT NULL UNIQUE,
                           employee_number VARCHAR(25) NOT NULL UNIQUE,
                           department_id BIGINT,
                           position VARCHAR(50) NOT NULL,
                           hire_date DATE NOT NULL,
                           status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ON_LEAVE', 'RESIGNED')),
                           profile_image_id BIGINT,
                           created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                           updated_at TIMESTAMPTZ,
                           FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE RESTRICT,
                           FOREIGN KEY (profile_image_id) REFERENCES files(id) ON DELETE SET NULL
);

-- 직원 수정 이력 테이블
CREATE TABLE change_logs (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             type VARCHAR(20) NOT NULL CHECK (type IN ('CREATED', 'UPDATED', 'DELETED')),
                             employee_id BIGINT NOT NULL,
                             employee_number VARCHAR(25) NOT NULL,
                             memo TEXT,
                             ip_address INET NOT NULL,
                             created_at TIMESTAMPTZ DEFAULT NOW(),
                             FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

-- 변경 상세 내용 테이블
CREATE TABLE change_log_diffs (
                                  change_log_id BIGINT NOT NULL,
                                  changes JSONB NOT NULL,
                                  PRIMARY KEY (change_log_id),
                                  FOREIGN KEY (change_log_id) REFERENCES change_logs (id) ON DELETE CASCADE
);

-- 백업 이력 테이블
CREATE TABLE backup_histories(
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 worker VARCHAR(100) NOT NULL,
                                 start_at TIMESTAMPTZ NOT NULL,
                                 ended_at TIMESTAMPTZ,
                                 status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS' CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED')),
                                 file_id BIGINT REFERENCES files (id),
                                 CHECK (
                                     (status = 'COMPLETED' AND file_id IS NOT NULL) OR
                                     (status = 'FAILED' AND file_id IS NOT NULL) OR
                                     (status IN ('IN_PROGRESS', 'SKIPPED') AND file_id IS NULL)
                                     )
);